apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-11-09T09:58:33Z"
  labels:
    app: private-reg
  name: private-reg
    
spec:
  clusterIP: 10.102.110.127
  clusterIPs:
  - 10.102.110.127
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31401
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: private-reg
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
