apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-11-09T09:58:33Z"
  labels:
    app: private-reg
  name: private-reg
    
spec:
  ports:
  - nodePort: 31402
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: private-reg
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
