apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5tb250cmFuLm$
kind: Secret
metadata:
  name: regcred-prod
  namespace: prod
type: kubernetes.io/dockerconfigjson
